### ISSUE TITLE
About the Embedding impedance's value

### ISSUE THREAD

**Issue by Chesire-W** [garrettj403/QMix#6]
Dear @garrettj403 

Just curious about why you set the impedance of RF and LO as 0.3-0.3j in multi-tone-simulation.

And do you have any suggestions to set these values while designing a SIS mixer?

C.W.

**Comment by garrettj403** [comment]
Hi @Chesire-W 

All of the voltages and impedances are normalized values (voltages normalized to the gap voltage and impedances normalized to the normal resistance).

0.3-0.3j roughly matches the SIS device that I was working on for my thesis. See Figure 3.24 here:
[https://ora.ox.ac.uk/objects/uuid:d47fbf3b-1cf3-4e58-be97-767b9893066e](https://ora.ox.ac.uk/objects/uuid:d47fbf3b-1cf3-4e58-be97-767b9893066e)

**Comment by Chesire-W** [comment]
Got it with lots of thanks!
